### ISSUE TITLE
Cannot be installed systemwide

### ISSUE THREAD

**Issue by darnir** [afonsoc12/firefly-cli#1]
The config file path is not configurable. It expects to be next to the source files

This prevents me from packaging it for Arch Linux to install system wide. 

Please store all information in `$XDG_CONFIG_HOME/firefly-cli` and `$XDG_DATA_HOME/firefly-cli`

**Comment by afonsoc12** [comment]
Hello @darnir,

Sorry for the delay but I did not have time before to look at this and thank you for pointing this out. 
It is now writing the configuration files in `$HOME/.firefly-cli/firefly.cli.ini` so it should suit your needs. Please test it with the latest commit and let me know if it worked (I have not released it to pip yet)

Best,
Afonso

**Comment by darnir** [comment]
Thanks for working on this!

However, may I please request that all new applications don't write to the user's `$HOME` directly, but rather follow the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html). For a basic explanation, please see [here](https://maex.me/2019/12/the-power-of-the-xdg-base-directory-specification/)

It is really easy to follow, but you could also just use the [xdg package](https://pypi.org/project/xdg/) on pypi to handle it for you

**Comment by afonsoc12** [comment]
Thank you for enlightening me. In fact I was not aware of this practice, although it seems great to unclutter $HOME folder. However, from what I can tell, it is not very well established.
I will publish a new release as soon as I setup the CI pipelines (still working on that).
